[package]
name = "dework"
version = "0.1.0"
authors = ["JasonZhou <zhoupw@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oscore={path="../../oscore"}
serde = {version = "1", features=["derive"] }
serde_json = "1"

